name: CI/CD Pipeline for EKS

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change this to your branch name
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ./build

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ./build
        
    - name: Build Docker image
      run: docker build -t karthikumarba/dna_webapp:${{ github.sha }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image
      run: docker push karthikumarba/dna_webapp:${{ github.sha }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update Kubernetes manifest
      run: |
        sed -i "s|image: karthikumarba/dna_webapp:.*|image: karthikumarba/dna_webapp:${{ github.sha }}|" deploy.yaml
        cat deploy.yaml
        
    - name: Commit updated manifest
      run: |
        git config user.name "KarthikKumarBA"
        git config user.email "bakarthikkumarba@gmail.com"
        git add deploy.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push

  deploy:
    runs-on: ubuntu-latest
    needs: update-manifest

    steps:
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Adjust to your AWS region

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: '1.30.0'  # Adjust to your kubectl version

    - name: Get EKS cluster credentials
      run: |
        aws eks update-kubeconfig --name karthik_eks_cluster --region ap-south-1
        kubectl config view --minify  # Ensure kubectl is properly configured

    - name: Deploy to EKS
      run: kubectl apply -f deploy.yaml
